---
general:
  host: 172.16.5.156
  port: 6668
  user: Tomochan
  nick: Tomochan
  real: Mint bot via Tiarra
  error: #Tomochan
  plugin_dir: plugins
  charset:
    default: utf-8

plugins:
  OpenPNENewDiaryCheck:
    sleep: 10
    uri: http://sns.es.occ.co.jp
    channel: '#Tomochan@occ'
    username: tomohiro
    password: rules7189
