# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mint}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tomohiro, TAIRA"]
  s.date = %q{2010-02-19}
  s.description = %q{Mint is A Ruby IRC Bot Pluggable Framework}
  s.email = %q{tomohiro.t@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "configs/example_environment.yaml",
     "configs/time_call.yaml",
     "example/sample.rb",
     "lib/mint.rb",
     "lib/plugin.rb",
     "lib/utils.rb",
     "mint.gemspec",
     "plugins/mixi_voice.rb",
     "plugins/openpne_new_diary_check.rb",
     "plugins/time_call.rb",
     "script/daemon",
     "script/server",
     "spec/mint_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/Tomohiro/mint}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{IRC Bot Framework}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/mint_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

