---
production:
  host: tiarra.example.com
  port: 6667
  user: Mitten
  nick: Mitten
  real: Mitten bot via Tiarra
  pass:
  channel: '#Mitten@example'
  plugin_dir: example # normal => plugins
  charset:
    default: utf-8
 
development:
  host: chat.freenode.net
  port: 6667
  user: Mitten
  nick: Mitten
  real: Mitten is IRC Bot Framework
  pass:
  channel: '#Mitten'
  plugin_dir: example # normal => plugins
  charset:
    default: utf-8
 
plugins:
  Sample:
    channel: '#Mitten@example'
