---
production:
  host: tiarra.example.com
  port: 6667
  user: Mint
  nick: Mint
  real: Mint bot via Tiarra
  pass:
  channel: '#Mint@example'
  plugin_dir: example # normal => plugins
  charset:
    default: utf-8
 
development:
  host: chat.freenode.net
  port: 6667
  user: Mint
  nick: Mint
  real: Mint is IRC Bot Framework
  pass:
  channel: '#Mint'
  plugin_dir: example # normal => plugins
  charset:
    default: utf-8
 
plugins:
  Sample:
    channel: '#Mint@example'
