---
production:
  host: chat.freenode.net
  port: 6667
  user: Mitten
  nick: Mitten
  real: Mitten is IRC Bot Framework
  pass:
  channel: '#Mitten'
  plugin_dir: example # normal => plugins
  charset:
    default: utf-8

development:
  host: my.irc.server.example.com
  port: 6667
  user: Mitten
  nick: Mitten
  real: Mitten is IRC Bot Framework
  pass:
  channel: '#Mitten'
  plugin_dir: plugins
  charset:
    default: utf-8

plugins:
  Echo:
    channel: '#Mitten'
    sleep: 10
