time:
  0900: '9時をお知らせするよ♪'
  1000: '10時をお知らせするよ♪'
  1100: '11時をお知らせするよ♪'
  1200: '12時をお知らせするよ♪'
  1300: '13時をお知らせするよ♪'
  1400: '14時をお知らせするよ♪'
  1500: '15時をお知らせするよ♪'
  1600: '16時をお知らせするよ♪'
  1700: '17時をお知らせするよ♪'
  1800: '18時をお知らせするよ♪'
  2100: '21時をお知らせするよ♪'
  0000: '深夜0時をお知らせするよ♪'
